language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  # Install bower, grunt and UI dependencies
  - npm install -g grunt bower
  - "(cd tests-cucumber-ui && npm install && bower install)"
